[[snippets]]
  description = "connect to vpn on macOS"
  command = "scutil --nc start <vpn=cloud-mgmt>"
  tag = ["macOS", "vpn"]
  output = ""

[[snippets]]
  description = "disconnect from vpn on macOS"
  command = "scutil --nc stop <vpn=cloud-mgmt>"
  tag = ["macOS", "vpn"]
  output = ""

[[snippets]]
  description = "list available network connection / check VPN status"
  command = "scutil --nc list"
  tag = ["macOS", "vpn"]
  output = ""

[[snippets]]
  description = "SIGKILL bugged tmux"
  command = "killall -9 tmux"
  tag = ["tmux"]
  output = ""

[[snippets]]
  description = "connect inv-stg gke cluster"
  command = "gcloud container clusters get-credentials inv-stg-cluster --zone asia-southeast1 --project asw-th-staging"
  tag = ["gke"]
  output = ""

[[snippets]]
  description = "forward argocd -> local"
  command = "kubectl port-forward svc/argocd-server -n argocd <port=8080>:443 --address 0.0.0.0"
  tag = ["k8s"]
  output = ""

[[snippets]]
  description = "connect bastion investment platform nonprod (enduring-stage-253308)"
  command = "gcloud config set account thanatchaya@robowealth.co.th; gcloud compute ssh bastion --internal-ip --zone asia-southeast1-a --project enduring-stage-253308"
  tag = ["gcp"]
  output = ""

[[snippets]]
  description = "connect bastion robowealth open api nonprod (robowealth-open-api)"
  command = "gcloud config set account thanatchaya@robowealth.co.th; gcloud compute ssh bastion --internal-ip --zone asia-southeast1-a --project robowealth-open-api"
  tag = ["gcp"]
  output = ""
