[[snippets]]
  description = "connect to asw-stg vpn"
  command = "scutil --nc start asw-stg"
  output = ""

[[snippets]]
  description = "list available network connection"
  command = "scutil --nc list"
  output = ""
